#!/usr/bin/python 

import sys
from twisted.application import internet, service
from twisted.internet import protocol, reactor, defer
from twisted.protocols import basic

sys.path.append('lib')
from legion.log import create_logger, log

if __name__ == '__main__':
    create_logger()

    master_port = 4200

    mf = MasterFactory()

    application = service.Application('legion', uid=1, gid=1)
    service_collection = service.IServiceCollection(application)
    internet.TCPServer(master_port, mf).setServiceParent(service_collection)
